### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by joan38** [daldridge/docusaurus-plugin-lunr#4]
```shell
$ npx @docusaurus/init@next init my-website classic
$ cd my-website/
$ npm install --save @aldridged/docusaurus-plugin-lunr
$ vi docusaurus.config.js # Add => plugins: ['@aldridged/docusaurus-plugin-lunr']
$ npm run build

> my-website@0.0.0 build /Users/jgoyeau/IdeaProjects/my-website
> docusaurus build

Creating an optimized production build...
Error: Cannot find module '@aldridged/docusaurus-plugin-lunr'
Require stack:
- /Users/jgoyeau/IdeaProjects/my-website
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
    at /Users/jgoyeau/IdeaProjects/my-website/node_modules/@docusaurus/core/lib/server/plugins/init.js:40:67
    at Array.map (<anonymous>)
    at Object.initPlugins (/Users/jgoyeau/IdeaProjects/my-website/node_modules/@docusaurus/core/lib/server/plugins/init.js:22:10)
    at Object.loadPlugins (/Users/jgoyeau/IdeaProjects/my-website/node_modules/@docusaurus/core/lib/server/plugins/index.js:47:28)
    at Object.load (/Users/jgoyeau/IdeaProjects/my-website/node_modules/@docusaurus/core/lib/server/index.js:57:62)
    at build (/Users/jgoyeau/IdeaProjects/my-website/node_modules/@docusaurus/core/lib/commands/build.js:59:34)
    at /Users/jgoyeau/IdeaProjects/my-website/node_modules/@docusaurus/core/bin/docusaurus.js:29:5
    at Command.<anonymous> (/Users/jgoyeau/IdeaProjects/my-website/node_modules/@docusaurus/core/bin/docusaurus.js:53:23)
    at Command.listener (/Users/jgoyeau/IdeaProjects/my-website/node_modules/commander/index.js:370:29)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (/Users/jgoyeau/IdeaProjects/my-website/node_modules/commander/index.js:892:12)
    at Command.parse (/Users/jgoyeau/IdeaProjects/my-website/node_modules/commander/index.js:642:21)
    at Object.<anonymous> (/Users/jgoyeau/IdeaProjects/my-website/node_modules/@docusaurus/core/bin/docusaurus.js:120:5)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
```

Any idea what step I missed?

**Comment by joan38** [comment]
Issue on docusaurus side:
https://github.com/facebook/docusaurus/issues/2831
